services:
  deno-gemini-grounding-mcp-server:
    build: .
    image: deno-gemini-grounding-mcp-server:latest
    container_name: deno-gemini-grounding-mcp-server-container
    environment:
      # Gemini API設定
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    # stdin/stdoutを有効にしてMCPサーバーとして動作
    stdin_open: true
    tty: true
    # 必要に応じてポートマッピングやボリュームマウントを追加
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - .:/app 